// <auto-generated />
using System;
using ControleBoleto.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ControleBoleto.Data.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20240118203929_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ControleBoleto.Domain.Banco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CodigoBanco")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("codigobanco");

                    b.Property<string>("NomeBanco")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomebanco");

                    b.Property<decimal>("PercentualJuros")
                        .HasColumnType("numeric")
                        .HasColumnName("percentualjuros");

                    b.HasKey("Id");

                    b.ToTable("bancos", (string)null);
                });

            modelBuilder.Entity("ControleBoleto.Domain.Boleto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BancoId")
                        .HasColumnType("uuid")
                        .HasColumnName("bancoid");

                    b.Property<string>("CpfCnpjBeneficiario")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cpfcnpjbeneficiario");

                    b.Property<string>("CpfCnpjPagador")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cpfcnpjpagador");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("datavencimento");

                    b.Property<string>("NomeBeneficiario")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomebeneficiario");

                    b.Property<string>("NomePagador")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nomepagador");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("observacao");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("BancoId");

                    b.ToTable("boletos", (string)null);
                });

            modelBuilder.Entity("ControleBoleto.Domain.Boleto", b =>
                {
                    b.HasOne("ControleBoleto.Domain.Banco", "Banco")
                        .WithMany("Boletos")
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("ControleBoleto.Domain.Banco", b =>
                {
                    b.Navigation("Boletos");
                });
#pragma warning restore 612, 618
        }
    }
}
